compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

injectEnvironmentFiles:
  - '.env.npm'

npmScopes:
  lukso-network:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN}"
