const PUBLIC_API_SHARED_SECRET = import.meta.env
  .VITE_APP_PUBLIC_API_SHARED_SECRET

const EMBEDDED_WALLET_URL = 
  import.meta.env.VITE_EMBEDDED_WALLET_URL || 'http://localhost:9100'

export { PUBLIC_API_SHARED_SECRET, EMBEDDED_WALLET_URL }
